name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn numpy scikit-learn

      - name: Run script
        run: |
          python Bank_DA.py > output.txt
          cat output.txt  # Show output in logs

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.txt


